services:
  yolov11:
    build: .
    container_name: yolo11-api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
    # Ressourcen-Limits (CPU-only)
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 2G